WebSite/Controllers/AreasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSite.Models;
using WebSite.serv;

namespace WebSite.Controllers
{ 
    public class AreasController : Controller
    {
        readonly IAreasRepositorio _areaRepositorio;

        public AreasController()
        {
            _areaRepositorio = new AreasRepositorio();
        }

        public AreasController(IAreasRepositorio repositorio)
        {
            _areaRepositorio = repositorio;
        }

        public ActionResult listarAreasTest()
        {
            var model = _areaRepositorio.ListarAreasT();
            return View(model);
        }

        sys_web_controlAsistenciaPersonalEntities db = new sys_web_controlAsistenciaPersonalEntities();
        
        public ActionResult Index()
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var query = (from a in db.AREAS select a).ToList();
                return View(query);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: Areas/Details/5
        public ActionResult Details(int id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: Areas/Create
        public ActionResult Create()
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                return View();
            }else
                {
                return RedirectToAction("Index", "Login");
            }
        }

        // POST: Areas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NOMBRE")]AREAS Model)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        db.AREAS.Add(Model);
                        db.SaveChanges();
                        this.Response.RemoveOutputCacheItem(Url.Action("Index").ToString());
                        return this.RedirectToAction("Index");
                    }
                    else
                    {
                        return View(Model);
                    }
                }
                catch (Exception ex)
                {
                    this.ModelState.AddModelError("", ex);
                    return View();
                }
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        

        // GET: Areas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var query = db.AREAS.Find(id);
                if (query == null)
                {
                    return this.HttpNotFound();
                }
                return View(query);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // POST: Areas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, AREAS areas)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var query = (db.AREAS.Find(id));
                if (query == null)
                {
                    return this.HttpNotFound();
                }
                if (!ModelState.IsValid)
                {
                    return View(areas);
                }
                if (!TryUpdateModel(query, new string[] { "NOMBRE" }))
                {
                    return View(areas);
                }
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex);
                    return View(areas);
                }
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: Areas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var query = db.AREAS.Find(id);
                if (query == null)
                {
                    return this.HttpNotFound();
                }
                return View(query);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // POST: Areas/Delete/5
        [HttpPost]
        
        [ActionName("Delete")]
        public ActionResult PostDelete(int id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var query = db.AREAS.Find(id);
                if (query != null)
                {
                    try
                    {
                        db.AREAS.Remove(query);
                        db.SaveChanges();

                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", ex);
                        return View(query);
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult Prueba()
        {
            ViewBag.Messa = "Prueba";
            return View();
        }

        public ActionResult Prueba2()
        {
            ViewBag.Messa = "Prueba";
            return View();
        }
    }

    
}

WebSite/Controllers/CARGOSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class CARGOSController : Controller
    {
        private sys_web_controlAsistenciaPersonalEntities db = new sys_web_controlAsistenciaPersonalEntities();

        // GET: CARGOS
        public ActionResult Index()
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var cARGOS = db.CARGOS.Include(c => c.AREAS);
                return View(cARGOS.ToList());
            }
            else {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: CARGOS/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                CARGOS cARGOS = db.CARGOS.Find(id);
                if (cARGOS == null)
                {
                    return HttpNotFound();
                }
                return View(cARGOS);
                }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: CARGOS/Create
        public ActionResult Create()
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                ViewBag.ID_AREA = new SelectList(db.AREAS, "ID_AREA", "NOMBRE");
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NOMBRE,ID_AREA")] CARGOS cARGOS)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (ModelState.IsValid)
                {
                    db.CARGOS.Add(cARGOS);
                    db.SaveChanges();
                    this.Response.RemoveOutputCacheItem(Url.Action("Index").ToString());
                    return RedirectToAction("Index");
                }

                ViewBag.ID_AREA = new SelectList(db.AREAS, "ID_AREA", "NOMBRE", cARGOS.ID_AREA);
                return View(cARGOS);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: CARGOS/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                CARGOS cARGOS = db.CARGOS.Find(id);
                if (cARGOS == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ID_AREA = new SelectList(db.AREAS, "ID_AREA", "NOMBRE", cARGOS.ID_AREA);
                return View(cARGOS);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_CARGOS,NOMBRE,ID_AREA")] CARGOS cARGOS)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(cARGOS).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ID_AREA = new SelectList(db.AREAS, "ID_AREA", "NOMBRE", cARGOS.ID_AREA);
                return View(cARGOS);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: CARGOS/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                CARGOS cARGOS = db.CARGOS.Find(id);
                if (cARGOS == null)
                {
                    return HttpNotFound();
                }
                return View(cARGOS);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // POST: CARGOS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                CARGOS cARGOS = db.CARGOS.Find(id);
                db.CARGOS.Remove(cARGOS);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebSite/Controllers/USUARIOSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class USUARIOSController : Controller
    {
        private sys_web_controlAsistenciaPersonalEntities db = new sys_web_controlAsistenciaPersonalEntities();

        // GET: USUARIOS
        public ActionResult Index()
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var uSUARIOS = db.USUARIOS.Include(u => u.EMPLEADOS);
                return View(uSUARIOS.ToList());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: USUARIOS/Details/5
        public ActionResult Details(string id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                USUARIOS uSUARIOS = db.USUARIOS.Find(id);
                if (uSUARIOS == null)
                {
                    return HttpNotFound();
                }
                return View(uSUARIOS);
            }
            else {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: USUARIOS/Create
        public ActionResult Create()
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                ViewBag.ID_EMPLEADO = new SelectList(db.EMPLEADOS, "ID_EMPLEADO", "DNI");
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_USUARIO,CONTRASEÑA,TIPO,ID_EMPLEADO,ACTIVO")] USUARIOS uSUARIOS)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (ModelState.IsValid)
                {
                    db.USUARIOS.Add(uSUARIOS);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.ID_EMPLEADO = new SelectList(db.EMPLEADOS, "ID_EMPLEADO", "DNI", uSUARIOS.ID_EMPLEADO);
                return View(uSUARIOS);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: USUARIOS/Edit/5
        public ActionResult Edit(string id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                USUARIOS uSUARIOS = db.USUARIOS.Find(id);
                if (uSUARIOS == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ID_EMPLEADO = new SelectList(db.EMPLEADOS, "ID_EMPLEADO", "DNI", uSUARIOS.ID_EMPLEADO);
                return View(uSUARIOS);
            }
            else {
                return RedirectToAction("Index", "Login");
            }
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_USUARIO,CONTRASEÑA,TIPO,ID_EMPLEADO,ACTIVO")] USUARIOS uSUARIOS)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(uSUARIOS).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ID_EMPLEADO = new SelectList(db.EMPLEADOS, "ID_EMPLEADO", "DNI", uSUARIOS.ID_EMPLEADO);
                return View(uSUARIOS);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: USUARIOS/Delete/5
        public ActionResult Delete(string id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                USUARIOS uSUARIOS = db.USUARIOS.Find(id);
                if (uSUARIOS == null)
                {
                    return HttpNotFound();
                }
                return View(uSUARIOS);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // POST: USUARIOS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                USUARIOS uSUARIOS = db.USUARIOS.Find(id);
                db.USUARIOS.Remove(uSUARIOS);
                db.SaveChanges();
                return RedirectToAction("Index");
            }else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebSite/Views/USUARIOS/Create.cshtml
@model WebSite.Models.USUARIOS

@{
    ViewBag.Title = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("~/Views/USUARIOS/_Partial_NavPills_Usuario.cshtml")

<div class="col-md-9">

    <h2>Crear nuevo usuario</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.Label("Usuario", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ID_USUARIO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ID_USUARIO, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Contraseña", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.CONTRASEÑA, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CONTRASEÑA, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Tipo", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TIPO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TIPO, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("ID Empleado", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ID_EMPLEADO, new { htmlAttributes= new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ID_EMPLEADO, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Activo", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.ACTIVO)
                        @Html.ValidationMessageFor(model => model.ACTIVO, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

    <div>
        <input type="button" value="Regresar" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "USUARIOS" )'" />
    </div>
    </div>

WebSite/Views/USUARIOS/Delete.cshtml
@model WebSite.Models.USUARIOS

@{
    ViewBag.Title = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("~/Views/USUARIOS/_Partial_NavPills_Usuario.cshtml")

<div class="col-md-9">
    <h2>Eliminar Usuarios</h2>

    <h3>¿Estas Seguro que desea eliminar el usuarios?</h3>
    <div>

        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("ID Usuario")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ID_USUARIO)
            </dd>

            <dt>
                @Html.DisplayName("Tipo");
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TIPO)
            </dd>

            <dt>
                @Html.DisplayName("Activo");
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ACTIVO)
            </dd>

            <dt>
                @Html.DisplayName("Empleado")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EMPLEADOS.NOMBRES)&nbsp;@Html.DisplayFor(model => model.EMPLEADOS.APELLIDOS)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Eliminar" class="btn btn-success" /> |
                <input type="button" value="Regresar" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "USUARIOS" )'" />
            </div>
        }
    </div>
    </div>

WebSite/Views/USUARIOS/Details.cshtml
@model WebSite.Models.USUARIOS

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("~/Views/USUARIOS/_Partial_NavPills_Usuario.cshtml")
<h2>Details</h2>

<div>
    <h4>USUARIOS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CONTRASEÑA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONTRASEÑA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIPO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIPO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ACTIVO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ACTIVO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMPLEADOS.DNI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMPLEADOS.DNI)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_USUARIO }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebSite/Views/USUARIOS/Edit.cshtml
@model WebSite.Models.USUARIOS

@{
    ViewBag.Title = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("~/Views/USUARIOS/_Partial_NavPills_Usuario.cshtml")
<div class="col-md-9">
    

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>USUARIOS</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID_USUARIO)

            <div class="form-group">
                @Html.LabelFor(model => model.CONTRASEÑA, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.CONTRASEÑA, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CONTRASEÑA, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TIPO, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TIPO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TIPO, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ID_EMPLEADO, "ID_EMPLEADO", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ID_EMPLEADO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ID_EMPLEADO, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ACTIVO, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.ACTIVO)
                        @Html.ValidationMessageFor(model => model.ACTIVO, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

    <div>
        <input type="button" value="Regresar" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "USUARIOS" )'" />
    </div>
    </div>

WebSite/Views/USUARIOS/Index.cshtml
@model IEnumerable<WebSite.Models.USUARIOS>

@{
    ViewBag.Title = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("~/Views/USUARIOS/_Partial_NavPills_Usuario.cshtml")
<div class="col-md-9">
    <h2>Listado de Usuarios</h2>

    <p>
        <input type="button" value="Crear nuevo usuario" class="btn btn-info" onclick="location.href='@Url.Action("Create", "USUARIOS" )'" />
    </p>
    <div class="table-responsive">
        <table class="table">
            <tr class="active">
                <th>
                    @Html.DisplayName("ID")
                </th>
                <th>
                    @Html.DisplayName("TIPO")
                </th>
                <th>
                    @Html.DisplayName("EMPLEADO")
                </th>
                <th>
                    @Html.DisplayName("ACTIVO")
                </th>
                <th>
                    @Html.DisplayName("ACCIONES")
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID_USUARIO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TIPO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EMPLEADOS.NOMBRES)&nbsp;@Html.DisplayFor(modelItem => item.EMPLEADOS.APELLIDOS)
                    </td>
                    <td>
                        @if (Convert.ToBoolean(item.ACTIVO.ToString()) == true)
                        {
                            @Html.DisplayName("SI")
                        }
                        else
                        {
                            @Html.DisplayName("NO")
                        }
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "USUARIOS", new {id = item.ID_USUARIO})">
                            <span class="glyphicon glyphicon-wrench" aria-hidden="true" title="EDITAR USUARIO"></span>
                        </a>|
                        <a href="@Url.Action("Delete", "USUARIOS", new { id = item.ID_USUARIO })">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true" title="ELIMINAR USUARIO"></span>
                        </a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

WebSite/Views/USUARIOS/_Partial_NavPills_Usuario.cshtml
<div class="col-md-3">
    <ul id="sidebar" class="nav nav-pills nav-stacked" style="max-width: 200px;">
        <li>
            <a href="@Url.Action("Casa", "Login")">
                <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                Inicio
            </a>
        </li>
        <li class="active">
            <a href="@Url.Action("Index", "USUARIOS")">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                Usuarios
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Areas")">
                <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>
                Areas
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "CARGOS")">
                <span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>
                Cargos
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "EMPLEADOS")">
                <span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>
                Empleados
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Asistencia")">
                <span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>
                Asistencia
            </a>
        </li>
    </ul>
</div>