WebSite/Controllers/AreasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSite.Models;
using WebSite.serv;

namespace WebSite.Controllers
{ 
    public class AreasController : Controller
    {
        readonly IAreasRepositorio _areaRepositorio;

        public AreasController()
        {
            _areaRepositorio = new AreasRepositorio();
        }

        public AreasController(IAreasRepositorio repositorio)
        {
            _areaRepositorio = repositorio;
        }

        public ActionResult listarAreasTest()
        {
            var model = _areaRepositorio.ListarAreasT();
            return View(model);
        }

        sys_web_controlAsistenciaPersonalEntities db = new sys_web_controlAsistenciaPersonalEntities();
        
        public ActionResult Index()
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var query = (from a in db.AREAS select a).ToList();
                return View(query);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: Areas/Details/5
        public ActionResult Details(int id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: Areas/Create
        public ActionResult Create()
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                return View();
            }else
                {
                return RedirectToAction("Index", "Login");
            }
        }

        // POST: Areas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NOMBRE")]AREAS Model)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        db.AREAS.Add(Model);
                        db.SaveChanges();
                        this.Response.RemoveOutputCacheItem(Url.Action("Index").ToString());
                        return this.RedirectToAction("Index");
                    }
                    else
                    {
                        return View(Model);
                    }
                }
                catch (Exception ex)
                {
                    this.ModelState.AddModelError("", ex);
                    return View();
                }
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        

        // GET: Areas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var query = db.AREAS.Find(id);
                if (query == null)
                {
                    return this.HttpNotFound();
                }
                return View(query);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // POST: Areas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, AREAS areas)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var query = (db.AREAS.Find(id));
                if (query == null)
                {
                    return this.HttpNotFound();
                }
                if (!ModelState.IsValid)
                {
                    return View(areas);
                }
                if (!TryUpdateModel(query, new string[] { "NOMBRE" }))
                {
                    return View(areas);
                }
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex);
                    return View(areas);
                }
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: Areas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var query = db.AREAS.Find(id);
                if (query == null)
                {
                    return this.HttpNotFound();
                }
                return View(query);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // POST: Areas/Delete/5
        [HttpPost]
        
        [ActionName("Delete")]
        public ActionResult PostDelete(int id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var query = db.AREAS.Find(id);
                if (query != null)
                {
                    try
                    {
                        db.AREAS.Remove(query);
                        db.SaveChanges();

                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", ex);
                        return View(query);
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult Prueba()
        {
            ViewBag.Messa = "Prueba";
            return View();
        }

        public ActionResult Prueba2()
        {
            ViewBag.Messa = "Prueba";
            return View();
        }
    }

    
}

WebSite/Controllers/AsistenciaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class AsistenciaController : Controller
    {
        private sys_web_controlAsistenciaPersonalEntities db = new sys_web_controlAsistenciaPersonalEntities();

        // GET: Asistencia
        public ActionResult Index()
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var query = db.EMPLEADOS.Include(e => e.AREAS).Include(e => e.CARGOS);
                return View(query);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult MarcarHora(int? id, EMPLEADOS empl)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (id != null)
                {
                    var query = db.EMPLEADOS.Find(id);
                    if (query != null)
                    {
                        string a = DateTime.Now.ToShortDateString();
                        var query2 = (db.ASISTENCIAS.Where(c => c.FECHA.Equals(a) && c.ID_EMPLEADO == id)).FirstOrDefault();
                        var query3 = (from c in db.ASISTENCIAS where c.FECHA.Equals(a) && c.ID_EMPLEADO == id select c).ToList();//(db.ASISTENCIAS.Where(c => c.FECHA == DateTime.Now && c.ID_EMPLEADO == id)).ToList();

                        string hora = DateTime.Now.ToString("hh:mm:ss");
                        if (query3.Count == 0)
                        {

                            var asis = new ASISTENCIAS();
                            asis.FECHA = a;
                            asis.ID_EMPLEADO = id;
                            asis.HORA_INGRESO = hora;
                            asis.HORA_SALIDA = "";
                            asis.OBSERVACIONES = "";
                            db.ASISTENCIAS.Add(asis);
                            db.SaveChanges();
                            ViewData["MenSal"] = "Ha marcado su hora de Entrada, Fecha: " + a + " Hora: " + hora;
                            return View();
                        }
                        else
                        {
                            if (query2.HORA_SALIDA == "")
                            {
                                query2.HORA_SALIDA = hora;
                                db.SaveChanges();
                                ViewData["MenSal"] = "Ha marcado su hora de Salida, Fecha: " + a + " Hora: " + hora;
                                return View();
                            }

                            return RedirectToAction("Index");
                        }
                    }
                }
                else
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
    }
}

WebSite/Controllers/EMPLEADOSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class EMPLEADOSController : Controller
    {
        private sys_web_controlAsistenciaPersonalEntities db = new sys_web_controlAsistenciaPersonalEntities();

        // GET: EMPLEADOS
        public ActionResult Index()
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var eMPLEADOS = db.EMPLEADOS.Include(e => e.AREAS).Include(e => e.CARGOS).Include(e => e.DISTRITOS);
                return View(eMPLEADOS.ToList());
            }
            else
            {
                return RedirectToAction("Index","Login");
            }
        }
        // GET: EMPLEADOS/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {

                if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    EMPLEADOS eMPLEADOS = db.EMPLEADOS.Find(id);
                    if (eMPLEADOS == null)
                    {
                        return HttpNotFound();
                    }
                    return View(eMPLEADOS);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: EMPLEADOS/Create
        public ActionResult Create()
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                ViewBag.ID_AREA = new SelectList(db.AREAS, "ID_AREA", "NOMBRE", "-1");
                ViewBag.ID_CARGO = new SelectList(new List<SelectListItem> { new SelectListItem { Selected = true, Text = string.Empty, Value = "-1" } }, "Value", "Text");//new SelectList(db.CARGOS, "ID_CARGOS", "NOMBRE");
                ViewBag.ID_DISTRITO = new SelectList(db.DISTRITOS, "ID_DISTRITO", "NOMBRE");
                return View();
            }
            else {
                return RedirectToAction("Index", "Login");
            }

        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DNI,NOMBRES,APELLIDOS,SEXO,HORA_INGRESO,HORA_SALIDA,ID_AREA,ID_CARGO,ID_DISTRITO,DIRECCION,TELEFONO,CELULAR")] EMPLEADOS eMPLEADOS)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (ModelState.IsValid)
                {
                    db.EMPLEADOS.Add(eMPLEADOS);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.ID_AREA = new SelectList(db.AREAS, "ID_AREA", "NOMBRE", eMPLEADOS.ID_AREA);
                ViewBag.ID_CARGO = new SelectList(db.CARGOS.Where(c => c.ID_AREA == eMPLEADOS.ID_AREA).ToList(), "ID_CARGOS", "NOMBRE", eMPLEADOS.ID_CARGO);
                ViewBag.ID_DISTRITO = new SelectList(db.DISTRITOS, "ID_DISTRITO", "NOMBRE", eMPLEADOS.ID_DISTRITO);
                return View(eMPLEADOS);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        [HttpGet]
        public ActionResult AjaxAreas_Cargos(int ID_AREA)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                var a = db.CARGOS.Where(c => c.ID_AREA == ID_AREA).ToList();
                var b = db.CARGOS.Find(ID_AREA);
                if (HttpContext.Request.IsAjaxRequest())
                {
                    return Json(db.CARGOS.Where(c => c.ID_AREA == ID_AREA).ToList().Select(c => new SelectListItem
                    {
                        Value = c.ID_CARGOS.ToString(),
                        Text = c.NOMBRE
                    }).ToList(), JsonRequestBehavior.AllowGet);
                }
                return View();
            }
            else {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: EMPLEADOS/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                EMPLEADOS eMPLEADOS = db.EMPLEADOS.Find(id);
                if (eMPLEADOS == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ID_AREA = new SelectList(db.AREAS, "ID_AREA", "NOMBRE", eMPLEADOS.ID_AREA);
                ViewBag.ID_CARGO = new SelectList(db.CARGOS, "ID_CARGOS", "NOMBRE", eMPLEADOS.ID_CARGO);
                ViewBag.ID_DISTRITO = new SelectList(db.DISTRITOS, "ID_DISTRITO", "NOMBRE", eMPLEADOS.ID_DISTRITO);
                return View(eMPLEADOS);
            }else{
                return RedirectToAction("Index", "Login");
            }
        }

        // POST: EMPLEADOS/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_EMPLEADO,DNI,NOMBRES,APELLIDOS,SEXO,HORA_INGRESO,HORA_SALIDA,ID_AREA,ID_CARGO,ID_DISTRITO,DIRECCION,TELEFONO,CELULAR")] EMPLEADOS eMPLEADOS)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(eMPLEADOS).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ID_AREA = new SelectList(db.AREAS, "ID_AREA", "NOMBRE", eMPLEADOS.ID_AREA);
                ViewBag.ID_CARGO = new SelectList(db.CARGOS.Where(c => c.ID_AREA == eMPLEADOS.ID_AREA), "ID_CARGOS", "NOMBRE", eMPLEADOS.ID_CARGO);
                ViewBag.ID_DISTRITO = new SelectList(db.DISTRITOS, "ID_DISTRITO", "NOMBRE", eMPLEADOS.ID_DISTRITO);
                return View(eMPLEADOS);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: EMPLEADOS/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                EMPLEADOS eMPLEADOS = db.EMPLEADOS.Find(id);
                if (eMPLEADOS == null)
                {
                    return HttpNotFound();
                }
                return View(eMPLEADOS);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // POST: EMPLEADOS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["MiUsuario"] != null && Session["MiTipo"] != null)
            {
                EMPLEADOS eMPLEADOS = db.EMPLEADOS.Find(id);
                db.EMPLEADOS.Remove(eMPLEADOS);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
    }
}

WebSite/Views/EMPLEADOS/Create.cshtml
@model WebSite.Models.EMPLEADOS

@{
    ViewBag.Title = "Empleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("~/Views/EMPLEADOS/_Partial_NavPills_Empleados.cshtml")
<div class="col-md-9">
    <h2>Crear Nuevo Empleado</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            
            <div class="form-group col-md-11">
                <div class="col-md-12">
                    @Html.LabelFor(model => model.DNI, htmlAttributes: new { @class = "col-md-12" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.DNI, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DNI, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            
            <div class="form-group col-md-6">    
                <div class="col-md-12">
                    @Html.LabelFor(model => model.NOMBRES, htmlAttributes: new { @class = "col-md-12" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.NOMBRES, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NOMBRES, "", new { @class = "text-danger" })
                    </div>
                </div>
           </div>
            
            <div class="form-group col-md-6">
                <div class="col-md-12">
                    @Html.LabelFor(model => model.APELLIDOS, htmlAttributes: new { @class = "col-md-12" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.APELLIDOS, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.APELLIDOS, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            
            <div class="form-group col-md-11">
                <div class="col-md-12">
                    @Html.LabelFor(model => model.SEXO, htmlAttributes: new { @class = "col-md-12" })
                    <div class="col-md-6">
                        <select class="form-control" id="SEXO" name="SEXO" class="form-control">
                            <option value="M">Masculino</option>
                            <option value="F">femenino</option>
                        </select>
                        @Html.ValidationMessageFor(model => model.SEXO, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

     <div class="form-group col-md-6">
         <div class="col-md-12">
             @Html.LabelFor(model => model.HORA_INGRESO, htmlAttributes: new { @class = "col-md-12" })
             <div class="col-md-12">
                 <input type="time" name="HORA_INGRESO" id="HORA_INGRESO" class="form-control">

                 @Html.ValidationMessageFor(model => model.HORA_INGRESO, "", new { @class = "text-danger" })
             </div>
         </div>
     </div>

     <div class="form-group col-md-6">
         <div class="col-md-12">
             @Html.LabelFor(model => model.HORA_SALIDA, htmlAttributes: new { @class = "col-md-12" })
             <div class="col-md-12">
                 <input type="time" name="HORA_SALIDA" id="HORA_SALIDA" class="form-control">

                 @Html.ValidationMessageFor(model => model.HORA_SALIDA, "", new { @class = "text-danger" })
             </div>
         </div>
     </div>

     <div class="form-group col-md-6">
         <div class="col-md-12">
             @Html.LabelFor(model => model.ID_AREA, "AREA", htmlAttributes: new { @class = "col-md-12" })
             <div class="col-md-12">
                 @Html.DropDownList("ID_AREA", null, "", htmlAttributes: new { @class = "form-control" })
                 @Html.ValidationMessageFor(model => model.ID_AREA, "", new { @class = "text-danger" })
             </div>
         </div>
     </div>

     <div class="form-group col-md-6">
         <div class="col-md-12">
             @Html.LabelFor(model => model.ID_CARGO, "CARGO", htmlAttributes: new { @class = "col-md-12" })
             <div class="col-md-12">

                 @Html.DropDownList("ID_CARGO", null, "", htmlAttributes: new { @class = "form-control" })
                 @Html.ValidationMessageFor(model => model.ID_CARGO, "", new { @class = "text-danger" })
             </div>
         </div>
     </div>

     <div class="form-group col-md-11">
         <div class="col-md-12">
             @Html.LabelFor(model => model.ID_DISTRITO, "DISTRITO", htmlAttributes: new { @class = "col-md-12" })
             <div class="col-md-6">
                 @Html.DropDownList("ID_DISTRITO", null, htmlAttributes: new { @class = "form-control" })
                 @Html.ValidationMessageFor(model => model.ID_DISTRITO, "", new { @class = "text-danger" })
             </div>
         </div>
    </div>

     <div class="form-group col-md-11">
         <div class="col-md-12">
             @Html.LabelFor(model => model.DIRECCION, htmlAttributes: new { @class = "col-md-12" })
             <div class="col-md-12">
                 @Html.EditorFor(model => model.DIRECCION, new { htmlAttributes = new { @class = "form-control col-md-12" } })
                 @Html.ValidationMessageFor(model => model.DIRECCION, "", new { @class = "text-danger" })
             </div>
         </div>
     </div>

     <div class="form-group col-md-6">
         <div class="col-md-12">
             @Html.LabelFor(model => model.TELEFONO, htmlAttributes: new { @class = "col-md-12" })
             <div class="col-md-12">
                 @Html.EditorFor(model => model.TELEFONO, new { htmlAttributes = new { @class = "form-control" } })
                 @Html.ValidationMessageFor(model => model.TELEFONO, "", new { @class = "text-danger" })
             </div>
         </div>
     </div>

     <div class="form-group col-md-6">
         <div class="col-md-12">
             @Html.LabelFor(model => model.CELULAR, htmlAttributes: new { @class = "col-md-12" })
             <div class="col-md-12">
                 @Html.EditorFor(model => model.CELULAR, new { htmlAttributes = new { @class = "form-control" } })
                 @Html.ValidationMessageFor(model => model.CELULAR, "", new { @class = "text-danger" })
             </div>
         </div>
    </div>

    <div class="form-group col-md-11">
        <div class="col-md-12">
            <div class="col-md-12">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>

    </div>
    }

    <div>
        <input type="button" value="Regresar" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "CARGOS" )'" />
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('#ID_AREA').change(function () {
            var cargos = $('#ID_AREA option:selected').val();
            $.ajax({
                type: 'GET',
                data: {ID_AREA: cargos},
                url: '@Url.Action("AjaxAreas_Cargos","EMPLEADOS")',
                
                success: function (result) {
                    var r = '';
                    for (var i = 0; i < result.length; i++) {
                        r += '<option value="' + result[i].Value + '">' + result[i].Text + '</option>';
                    }
                    $('#ID_CARGO').html(r);
                }
            });
        });
    });
</script>

WebSite/Views/EMPLEADOS/Delete.cshtml
@model WebSite.Models.EMPLEADOS

@{
    ViewBag.Title = "Empleados";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("~/Views/EMPLEADOS/_Partial_NavPills_Empleados.cshtml")

<div class="col-md-9">
    <h3>¿Estas seguro de eliminar este registro?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.DNI)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DNI)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NOMBRES)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NOMBRES)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.APELLIDOS)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.APELLIDOS)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SEXO)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SEXO)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HORA_INGRESO)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HORA_INGRESO)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HORA_SALIDA)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HORA_SALIDA)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DIRECCION)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DIRECCION)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TELEFONO)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TELEFONO)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CELULAR)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CELULAR)
            </dd>

            <dt>
                @Html.DisplayName("AREAS")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AREAS.NOMBRE)
            </dd>

            <dt>
                @Html.DisplayName("CARGOS")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CARGOS.NOMBRE)
            </dd>

            <dt>
                @Html.DisplayName("DISTRITOS")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DISTRITOS.NOMBRE)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Eliminar" class="btn btn-success"/> |
                <input type="button" value="Regresar" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "EMPLEADOS")'" />
            </div>
        }
    </div>
</div>

WebSite/Views/EMPLEADOS/_Partial_NavPills_Empleados.cshtml
<div class="col-md-3">
    <ul id="sidebar" class="nav nav-pills nav-stacked" style="max-width: 200px;">
        <li>
            <a href="@Url.Action("Casa", "Login")">
                <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                Inicio
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "USUARIOS")">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                Usuarios
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Areas")">
                <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>
                Areas
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "CARGOS")">
                <span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>
                Cargos
            </a>
        </li>
        <li class="active">
            <a href="@Url.Action("Index", "EMPLEADOS")">
                <span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>
                Empleados
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Asistencia")">
                <span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>
                Asistencia
            </a>
        </li>
    </ul>
</div>